### ISSUE TITLE
Issue with PCAir - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by AmandaHWChong** [UW-GAC/GENESIS#106]
Hi, 

I am trying to run the pcair function, however when I do I get this error "Segmentation fault (core dumped)". Could you please advise me on how to troubleshoot the issue? 

My R session is as below: 

R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(GENESIS)
library(GWASTools)
library(gdsfmt)
library(SNPRelate)
library(data.table)
library(dplyr)

> KING <- fread("king.kin0")
> KING <- as.data.frame(KING)
> KINGmat <- matrix(
  data = KING$Kinship,
  nrow = length(KING$FID1),
  ncol = length(KING$FID2),
  byrow = TRUE,
  dimnames = list(KING$FID1, KING$FID2)
)
> geno <- GdsGenotypeReader(filename = "genotype.gds")
genoData <- GenotypeData(geno)
> pruned <- fread("pruned.txt")
pruned <- as.data.frame(pruned)
pruned <- as.vector(pruned)
unrels <- fread("king_unrelated.txt")
unrels <- as.data.frame(unrels)
unrels <- as.vector(unrels)
> mypcair <-pcair(genoData, kinobj= KINGmat,divobj = KINGmat,snp.include = pruned, verbose=T, eigen.cnt=10, unrel.set = unrels)
Using kinobj and divobj to partition samples into unrelated and related sets
Working with 107828 samples
Identifying relatives for each sample using kinship threshold 0.0220970869120796
Segmentation fault (core dumped)

Thank you for your help!

**Comment by smgogarten** [comment]
My first suggestion is not to load `dplyr` and `data.table` in the same R session - they are not compatible so I've seen bad things happen when they are used together.

However, I think the error comes from your matrix being much too large for `pcair` to handle as standard R matrix. Use the function `kingToMatrix` instead to read your kinship file into a sparse matrix object.

**Comment by AmandaHWChong** [comment]
Hi, 

I have tried to read in my king.kin0 file with the kingToMatrix function but I get this error 'Error in (function (classes, fdef, mtable)  :  unable to find an inherited method for function 'kingToMatrix' for signature '"data.frame"'. Is there a better way of reading in the file so that it is compatible with the kingToMatrix function? 

Here is my code: 
R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(GENESIS)
library(GWASTools)
library(gdsfmt)
library(SNPRelate)
> KING <- read.table("king.kin0", header = T)
> KINGmat <- kingToMatrix(KING, estimator = "Kinship")
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function 'kingToMatrix' for signature '"data.frame"'
> KING <- as.class(KING)
Error in as.class(KING) : could not find function "as.class"

Thank you for your help!
