### ISSUE TITLE
Issue: Running PCAir on 140K individuals

### ISSUE THREAD

**Issue by AmandaHWChong** [UW-GAC/GENESIS#107]
Hi, 

I have been running the pcair() function on 140K individuals for 3 days and it doesn't look like it is making any progress. Could this be a sample size issue or a memory issue? 

As you see below: 
Reading in Kinship estimates from KING --kinship output...
Using 140831 samples in sample.include
Identifying clusters of relatives...
    82438 relatives in 21768 clusters; largest cluster = 9653
Creating block matrices for clusters...
58393 samples with no relatives included
Putting all samples together into one block diagonal matrix
Using kinobj and divobj to partition samples into unrelated and related sets
Working with 140831 samples
Identifying relatives for each sample using kinship threshold 0.0441941738241592
Identifying pairs of divergent samples using divergence threshold -0.0441941738241592
Partitioning samples into unrelated and related sets...
    ...1000 samples added to related.set...
    ...2000 samples added to related.set...
    ...3000 samples added to related.set...
    ...4000 samples added to related.set...
    ...5000 samples added to related.set...
    ...6000 samples added to related.set...
    ...7000 samples added to related.set...
    ...8000 samples added to related.set...
    ...9000 samples added to related.set...
    ...10000 samples added to related.set...
    ...11000 samples added to related.set...
    ...12000 samples added to related.set...
    ...13000 samples added to related.set...
    ...14000 samples added to related.set...
    ...15000 samples added to related.set...
    ...16000 samples added to related.set...
    ...17000 samples added to related.set...
    ...18000 samples added to related.set...
    ...19000 samples added to related.set...
    ...20000 samples added to related.set...
    ...21000 samples added to related.set...
    ...22000 samples added to related.set...
    ...23000 samples added to related.set...
    ...24000 samples added to related.set...
    ...25000 samples added to related.set...
    ...26000 samples added to related.set...
    ...27000 samples added to related.set...
    ...28000 samples added to related.set...
    ...29000 samples added to related.set...
    ...30000 samples added to related.set...
    ...31000 samples added to related.set...
    ...32000 samples added to related.set...
    ...33000 samples added to related.set...
    ...34000 samples added to related.set...
    ...35000 samples added to related.set...
    ...36000 samples added to related.set...
    ...37000 samples added to related.set...
    ...38000 samples added to related.set...
    ...39000 samples added to related.set...
    ...40000 samples added to related.set...
    ...41000 samples added to related.set...
    ...42000 samples added to related.set...
    ...43000 samples added to related.set...
    ...44000 samples added to related.set...
    ...45000 samples added to related.set...
    ...46000 samples added to related.set...
    ...47000 samples added to related.set...
Unrelated Set: 93272 Samples
Related Set: 47559 Samples
Performing PCA on the Unrelated Set...
Principal Component Analysis (PCA) on genotypes:
Excluding 7,660,980 SNPs (non-autosomes or non-selection)
Excluding 0 SNP (monomorphic: TRUE, MAF: NaN, missing rate: NaN)
    # of samples: 93,272
    # of SNPs: 280,707
    using 1 thread
    # of principal components: 20
PCA:    the sum of all selected genotypes (0,1,2) = 4401574483
CPU capabilities: Double-Precision SSE2 AVX
Tue Jan  9 18:06:54 2024    (internal increment: 64)

Thank you for your help.

**Comment by smgogarten** [comment]
This is probably because your sample size is so large. There are two things you can do to improve performance:
1. Use the argument `algorithm='randomized'` to run a faster PCA algorithm 
2. Use the argument `num.cores=n` where `n` depends on your machine
