### ISSUE TITLE
Error in setMethod - no existing definition for function ‘chromWithPAR’

### ISSUE THREAD

**Issue by David-Duffy** [UW-GAC/GENESIS#11]
Hi.

When I try to install the current version (Version: 2.13.3 Date: 2019-1-30), I am getting

Error in setMethod("chromWithPAR", "GenotypeData", function(gdsobj) { : 
  no existing definition for function ‘chromWithPAR’

coming from utils.R.  Is one of my other packages out of date or something?

Thanks, David Duffy.

**Comment by smgogarten** [comment]
You need to install the [SeqVarTools](https://github.com/smgogarten/SeqVarTools) package first.

If you have any other installation problems, make sure you are using the latest R version (>=3.5.0), then follow the [instructions for installing Bioconductor packages](http://www.bioconductor.org/install/) to get the release version of GENESIS. Unless you are trying to use a brand-new feature (imputed dosage support is the only one at the moment), I recommend using the release version of the package.
