### ISSUE TITLE
Available rare variant aggregate association tests

### ISSUE THREAD

**Issue by CristianRiccio** [UW-GAC/GENESIS#113]
Hello,
Are these the available rare variant aggregate association tests?
BinomiRare, burden, CMP test, fastSKAT, fastSMMAT, SKAT, SKAT-O, SMMAT

and are 
BinomiRare, CMP test, Score, SPA test
the tests available for single-marker tests?

Does BinomiRare aggregate variants in a set or testing unit? How can I choose the testing unit?

Thanks, and best wishes,
Cristian.

**Comment by smgogarten** [comment]
That is correct. All the aggregate tests define testing units with a SeqVarIterator object, which can be defined in various ways: blocks, sliding windows, and GRanges objects. See the [documentation in the SeqVarTools package](https://bioconductor.org/packages/release/bioc/vignettes/SeqVarTools/inst/doc/Iterators.pdf) for more information on how to construct these objects.
