### ISSUE TITLE
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) :   object 'saddle' not found

### ISSUE THREAD

**Issue by ruuhsu** [UW-GAC/GENESIS#114]
Hello,

I use the window sliding method to do a SKAT-O test using GENESIS. Here's an error I kept getting and can't seem to find the answer anywhere.

assoc <- assocTestAggregate(iterator, nullmod, test="SKATO")

Error in get(name, envir = asNamespace(pkg), inherits = FALSE) :
  object 'saddle' not found

I would appreciate if someone could shed some light on this.. thank you!

**Comment by smgogarten** [comment]
The [survey](https://cran.r-project.org/web/packages/survey/index.html) package is required for SKAT-O tests. Please try installing it and restarting your R session.

**Comment by ruuhsu** [comment]
Hello Stephanie, 

Thank you for getting back to me! After activating the survey package, I am still encountering the same issues. I am using R/4.0.5 and I am wondering if other things might be related to this issue. I have reinstalled SKAT package a couple of times as well.

Thank you!

**Comment by smgogarten** [comment]
R 4.0.5 is several years old at this point, so there may be mismatches between the versions of the packages you are trying to install and your R version. Please try upgrading to the current version of R.
