### ISSUE TITLE
how to check the assumption of poisson regression

### ISSUE THREAD

**Issue by yu-zhang-oYo** [UW-GAC/GENESIS#117]
Hi,
The outcome in my data is 0, 1,2 ,3,4,..., I tried to use poisson family, but how can I check if it is suitable to use poisson regression with this package? if it is overdispersion, is there any way to solve this problem with this package?
Thanks

**Comment by mconomos** [comment]
The poisson family is available in fitNullModel for analyzing count data, as you noted. If you want to evaluate the suitability of the model to your data, I would suggest making whatever diagnostic plots you typically make after fitting a poisson regression. The $fit object in the output of fitNullModel contains various residuals and fitted values that could be used to construct these diagnostic plots. The package does not currently have an option for overdispersion.
