### ISSUE TITLE
assocTestSingle SeqVarBlockIterator - problem handling multiallelic sites

### ISSUE THREAD

**Issue by David-Duffy** [UW-GAC/GENESIS#13]
Hi, I am having problems (that I will work around by removing the nuisance marker) running

assocTestSingle(iterator, null1, verbose=TRUE)
where iterator is a SeqVarBlockIterator

I am trying this on a test region where one locus has five alleles (and 5 are monomorphic):

var.info <- variantInfo(gdsobj, alleles = FALSE, expanded = TRUE)

has 106 rows, while

 geno <- expandedAltDosage(gdsobj, use.names = FALSE, sparse = sparse)[sample.index, 
    , drop = FALSE]
dim(expandedAltDosage(gdsobj, use.names = FALSE, sparse = sparse))
[1] 2391  114

has 114 alleles, which seems right to me.

But as a result, 

res[[i]] <- cbind(var.info, n.obs, freq, assoc)
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 106, 114

I am presuming variantinfo(expanded=T) should replicate the positions for each allele?

TIA,
David Duffy

**Comment by smgogarten** [comment]
`variantInfo(expanded=T)` should indeed replicate positions for each allele, so I'm surprised it's not working in this case. Is it possible for you to share this small bit of data so I can debug? If not, could you run `nAlleles(gdsobj)` and see if it gives you the expected results (2 for each biallelic site, higher values for multiallelic sites)? You could also try running `variantInfo(gdsobj, alleles = TRUE, expanded = TRUE)` and compare the results with `alleles = FALSE`. The function uses a different method to expand the data.frame in each case, so the comparison might be informative in debugging.

**Comment by smgogarten** [comment]
The bug was not in handling the multiallelic variants, but rather that variants with no alternate alleles were being dropped from `variantInfo`. Fixed in SeqVarTools release v1.20.2 and devel v1.21.3. Thanks for the report!
