### ISSUE TITLE
variable names with "SE" or "Est" crash

### ISSUE THREAD

**Issue by jonaszierer** [UW-GAC/GENESIS#24]
When running `assocTestSingle` with a `GxE` effct (though I suppose the problem would be the same without) I got the error message

```
Error in res[g, grep("SE", colnames(res))] <- sqrt(diag(Vbetas)) :
    number of items to replace is not a multiple of replacement length
```

along with

```
In addition: Warning message:
In grep(paste0("^", col.name), colnames(null.model$model.matrix)) :
  argument 'pattern' has length > 1 and only the first element will be used
```

Trurns out that in `.testGenoSingleVarWaldGxE`  standard errors are set by ` res[g, grep("SE", colnames(res))] <- sqrt(diag(Vbetas))`. If any of the names of covariates matches `SE` (e.g. `SEX`) the regex also matches `Est.G.SEX` which leads to incorrect number of values. 

I don't think the regex thing is ideal but changing it to something like `^SE\\.G"` should make it a bit more robust.

**Comment by smgogarten** [comment]
Thanks! Fixed in ef02213 and pushed to release v2.14.2
