### ISSUE TITLE
Bug with GxE when using GenotypeIterator

### ISSUE THREAD

**Issue by jonaszierer** [UW-GAC/GENESIS#26]
In `assocTestSingle` for `GenotypeIterator` it iterates over the SNP blocks. In each iteration `GxE` (the name of ithe interaction effects) is set to the model matrix.

```if (!is.null(GxE)) GxE <- .modelMatrixColumns(null.model, GxE)```

 That works in the fist iteration when `GxE` is still a character but fails in the second iteration where `GxE` is already a model matrix. This should probably be moved outside the loop or changed to 

```
if (!is.null(GxE)) GxE_m <- .modelMatrixColumns(null.model, GxE) 
assoc <- GENESIS:::testGenoSingleVar(null.model, G=geno, E=GxE_m, test=test)
```

(Though I can't really see a reson not to move it to before the start of the loop)

**Comment by smgogarten** [comment]
Thanks, fixed in 687ad1c and release v2.14.3
