### ISSUE TITLE
PCAir unable to proceed when there are no related individuals

### ISSUE THREAD

**Issue by seunghun23** [UW-GAC/GENESIS#29]
Hello, 

I am encountering following error when running PCAir on some of my cohorts, and it looks
like I get this error when there are no related individuals. Could you help me on this issue? 

Thanks,
Seunghun 

![image](https://user-images.githubusercontent.com/38226390/62485526-f0830900-b78a-11e9-887e-d6b5a1712433.png)

**Comment by smgogarten** [comment]
pcair should return a list with `$rels` `NULL` in the case of no relatives. Could you provide some more context (what code did you run leading up to this error), and also sessionInfo()?

**Comment by seunghun23** [comment]
Below is the code, and I can not provide with sessionInfo() for now because one of my
colleague ran the script, and he did with a small vcf of his which includes only 11 samples (probably all unrelated with each other). The same script ran fine with larger vcfs before. 
 
-------------------------------------------------------------------------------------
seqVCF2GDS(vcf_input,"temp.gds", verbose=FALSE)
gds<- seqOpen("temp.gds")

snpset <- snpgdsLDpruning(gds, method="corr", slide.max.bp=10e6,
                          ld.threshold=sqrt(0.1), verbose=FALSE)
pruned <- unlist(snpset, use.names=FALSE)
king <- snpgdsIBDKING(gds, snp.id=pruned, verbose=FALSE)
kingMat <- king$kinship
dimnames(kingMat) <- list(king$sample.id, king$sample.id)


pcs <- pcair(gds,
             kinobj=kingMat, kin.thresh=2^(-9/2),
             divobj=kingMat, div.thresh=-2^(-9/2),
             snp.include=pruned)

**Comment by smgogarten** [comment]
pcairPartition (the function that selects an unrelated set) will run on a sample set that small (even with no relatives), so I suspect the problem might have arisen farther upstream in the script (as in, the inputs to the pcair function were not valid). But 11 samples is such a small number that I'm not sure it makes sense to run this analysis on them.
