### ISSUE TITLE
pcrelate parallel implementation

### ISSUE THREAD

**Issue by dleopold** [UW-GAC/GENESIS#41]
The help documentation for pcrelate() suggests that parallelization is possible using the component functions calcISAFBeta() and pcrelateSampBlock(). I hope I am not being completely daft, but I am struggling to set up a parallel implementation. How can this be done?

**Comment by smgogarten** [comment]
This recently closed issue answers the same question: https://github.com/UW-GAC/GENESIS/issues/38

**Comment by dleopold** [comment]
Thank you for pointing me to the answer.
