### ISSUE TITLE
varCompCI gives a heritability of 0

### ISSUE THREAD

**Issue by yanglipmed** [UW-GAC/GENESIS#46]
I met that varCompCI function gave heritability of 0 several times. Proportion is 0. Lower 95 and Upper 95 are NA. I used command: varCompCI(nullmod, prop = TRUE). My nullmod matrix seems no problem.
Is this reasonable?

My case is neither of the following two unsuitable situations as GENESIS manual mentions:
#####################################################################################
Note: varCompCI can not compute proportions of variance explained when heterogeneous residual variances are used in the null model (i.e. group.var is used in fitNullModel). Confidence intervals can still be computed for the variance component estimates on the original scale by setting prop = FALSE.

Note: variance component estimates are not interpretable for binary phenotypes when fit using the PQL method implemented in fitNullModel; proportions of variance explained should not be calculated for these models.

**Comment by mconomos** [comment]
Could you please look at the variance component estimates directly from your null model? If your null model is loaded in R as `nullmod`, then print `nullmod$varComp`. If the variance component for your GRM (or kinship matrix) is 0, then the heritability estimate will be 0. If you have an example where the variance component is *not* 0, but `varCompCI` is still returning a 0 estimate, please let me know, and I can look into it.

**Comment by yanglipmed** [comment]
Sorry to forget to reply you. The variance component for GRM is zero. GRM matrix seems normal. Is it reasonable to get a variance of zero?
Thanks.

**Comment by mconomos** [comment]
It's certainly mathematically possible to get a variance component of 0 for the GRM, but I think it's somewhat unlikely for a real phenotype. A variance component of 0 for the GRM means that the trait is not heritable. If you think something is going wrong, you can share your code, and I can see if I see anything that looks wrong.
