### ISSUE TITLE
parallel implementation of pcrelate

### ISSUE THREAD

**Issue by dleopold** [UW-GAC/GENESIS#47]
The functions, `correctKin`, `correctK0`, `correctK2`, do not seem to work. I have been trying to follow the instructions provided in issue #38, to set up a parallel implementation of pcrelate. However, because these functions do not work, I am not sure how to do the post-processing. Also, the `correctKin` function is not actually used in the scripts referenced in the answer to that issue. Is it needed? Any guidance on the use of these functions to combine output of the calls to `pcrelateSampBlock` would be greatly appreciated. Thank you.

**Comment by mconomos** [comment]
Hello. Could you please send the code you are using in your script to try to run these functions, and/or the errors you are encountering? I would be happy to try to help diagnose the issue.  

The `correctKin` function is only used when you are using the `small.samp.correct` parameter. If you are running a parallel implementation, you won't use it. If you want better IBD probability estimates, you should use the `correctK0` and `correctK2` functions.

**Comment by dleopold** [comment]
The code is more or less identical to the code [here](https://github.com/UW-GAC/analysis_pipeline/blob/master/R/pcrelate_correct.R). When I run the steps that use `correctK0` or `correctK2`, nothing is returned, so the `res$kinBtwn` emptied as opposed to corrected. There are no errors, and if I run the function directly (ie without directing the output somewhere) it does not print anything to the terminal (not even a `NULL` value). I have tried both the stable release and installing the development version directly from github.

**Comment by mconomos** [comment]
Is it possible for you to share the head of your kinBtwn and kinSelf results that you're using as input? That might help me identify the issue.
