### ISSUE TITLE
K0 values greater than 1

### ISSUE THREAD

**Issue by sstadick** [UW-GAC/GENESIS#56]
Hello!

I've been rereading the vignettes and paper and noticed that K0 is > 1 in the vignette: http://bioconductor.org/packages/devel/bioc/vignettes/GENESIS/inst/doc/pcair.html#output-from-pc-relate. Given that K0 is the probability of sharing 0 alleles, how can it be greater than 1? I've noticed this in my own data as well, even after applying the correction functions.

**Comment by mconomos** [comment]
Hi!

You are correct that K0 estimates from PC-Relate can be greater than 1. Each of K0, K1, K2, and kinship are defined as probabilities, and hence are restricted to [0,1] in truth. However, the method of moments (MOM) estimators that PC-Relate implements do not enforce those boundary conditions. This is fairly common for MOM based estimators of genetic relatedness (e.g. KING-robust, GCTA), and was a decision we made in implementing PC-Relate. 

If you want to restrict your estimates, you could of course truncate K estimates to be in [0,1]. (Note also that K0 + K1 + K2 = 1 in truth, but won't necessarily hold with the PC-Relate estimators, and won't necessarily hold if you truncate estimates). Also, I would _not_ truncate kinship values if you are using them in a kinship matrix for association testing - negative values are meaningful in this context. 

Hope this helps.
