### ISSUE TITLE
change use of apply in makeSparseMatrix to GENESIS:::.apply

### ISSUE THREAD

**Issue by mchughc** [UW-GAC/GENESIS#58]
if one wants to use the makeSparseMatrix function with a Matrix, the call to 'apply' on line 72 will fail with 'cholMod error too large' in some cases. i propose using GENESIS:::.apply (need to add a 'selection' argument) which would handle all cases!

thanks :)

**Comment by smgogarten** [comment]
Fixed in [ed5316c](https://github.com/UW-GAC/GENESIS/commit/ed5316c3bc5fdc7fc2090f2877ddef5b921f0453)
