### ISSUE TITLE
Issue with GxE interaction with Score test in assocTestSingle

### ISSUE THREAD

**Issue by d1eone** [UW-GAC/GENESIS#61]
When running GENESIS v. 2.13.11 and supplying an interactive term for the score test, I get the following error after all iterations are completed:

> Error in match.names(clabs, names(xi)) : 
>   names do not match previous names
> Calls: source ... .local -> do.call -> <Anonymous> -> rbind -> match.names
> In addition: There were 50 or more warnings (use warnings() to see the first 50)
> Execution halted

It appears from the log, that Wald is done for the interaction test and Score for the genetic effect, but then at the end something happens when the rows are combined using rbind.  

Here is my code:

```
 seqSetFilterChrom(SeqData, include = CHR)
    SeqIterator <- SeqVarBlockIterator(SeqData, variantBlock=5000)
    

    RequestedMixedModel = assocTestSingle(SeqIterator, 
                                          imputed = TRUE, 
                                          null.model = get(Ho), 
                                          # test = "Score",
                                          GxE = InteractionTerm
    )
    resetIterator(SeqIterator)
```
Ho represents the null model, which include PCs and a variable for maternal haplogroup. Outcome a binary variable, and I am modeling the effect of imputed variants.

Is this something that was addressed in more recent versions of GENESIS?

**Comment by smgogarten** [comment]
Yes, I believe this bug has been fixed in the current GENESIS version. I don't remember exactly which version, but it was at least a year ago.
