### ISSUE TITLE
Generate Dense Kinship matrix

### ISSUE THREAD

**Issue by nkurniansyah** [UW-GAC/GENESIS#67]
Hello,

I trying to generate dense kinship matrix. How to return dense kinship matrix using (pcrelateToMatrix)?

Thank you,

**Comment by smgogarten** [comment]
Set `thresh=NULL` (which is the default behavior).

**Comment by nkurniansyah** [comment]
Thanks for the response. 

I set thresh=NULL, but still return sparse.

Thank you.
