### ISSUE TITLE
assocTestSingle.R() error when interacting with GenotypeIterator / GenotypeBlockIterator objects

### ISSUE THREAD

**Issue by AAvalos82** [UW-GAC/GENESIS#7]
I was unsure where to raise this issue since the error is specific to `assocTestSingle.R()` but stems from different method calls of `getGenotypeSelection()` from the GWASTools package.

In `assocTestSingle.R()`, line 83, `getGenotypeSelection()` is being called with `order = "selection"`. This argument is undefined in the methods for `getGenotypeSelection()` extracting information from `MatrixGenotypeReader` class objects or `GenotypeIterator` / `GenotypeBlockIterator` objects constructed using `MatrixGenotypeReader`. This produces the error: "Error in .local(object, ...) : unused argument (order = "selection")".

Is the intent for the function to only work only with `GenotypeIterator` / `GenotypeBlockIterator` objects constructed from `GdsGenotypeReader` objects? If so, this needs to be specified in the documentation for `assocTestSingle.R()`. Alternatively, if the intent is for the function to also work with output constructed from `MatrixGenotypeReader` objects, then this is a valid issue for `assocTestSingle.R()`.

**Comment by AAvalos82** [comment]
Update, modifying the `assocTestSingle.R()` function call to exclude the `order = "selection"` argument when `class(gdsobj@data) == "MatrixGenotypeReader"` worked without a problem. I am sure a more elegant solution can be applied to be mindful of the API variation in `getGenotypeSelection()`.

**Comment by smgogarten** [comment]
Fixed in GWASTools via https://github.com/smgogarten/GWASTools/commit/7d268033686b968c22135850215654019b0d5cdc. Also added documentation and a unit test in https://github.com/UW-GAC/GENESIS/commit/4c25a5f28be6267d5e7345abce6388c0578802c6
